image: gitpod/workspace-full
checkoutLocation: gitpod-k3s
tasks:
  - name: prepare k3s
    command: |
      .gitpod/prepare-k3s.sh
  - name: kernel dev environment
    init: |
      sudo apt update -y
      sudo apt upgrade -y
      sudo apt update -y
      sudo apt install qemu qemu-system-x86 linux-image-generic libguestfs-tools sshpass netcat -y
      .gitpod/prepare-rootfs.sh
    command: |
      mkdir ~/.kube/config
      sudo curl -o /usr/bin/kubectl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      sudo chmod +x /usr/bin/kubectl
      .gitpod/wait-ssh.sh && sshpass -p root scp -P 2222  root@127.0.0.1:/etc/rancher/k3s/k3s.yaml   ~/.kube/config &
      .gitpod/qemu.sh      